xcube version upgrade to 0.9.1 and xcube-cci 0.9.0
CCI-Tools/cate pull request #1018
Opened 2021-11-04 09:25 UTC by AliceBalfanz

When accepting this PR, cate will

    run with xcube  version 0.9.1 and xcube-cci version 0.9.0
    have a simplified Dockerfile based on quay.io/bcdev/xcube:v0.9.1

2021-11-04 09:43 UTC, forman requested changes

2021-11-04 09:43 UTC, forman commented on cate/core/ds.py
> +from xcube.core.store import MutableDataStore, DATASET_TYPE
```suggestion
from xcube.core.store import DATASET_TYPE
from xcube.core.store import MutableDataStore
```

2021-11-04 09:43 UTC, forman commented on environment.yml
> +  - python>=3.7
```suggestion
  - python>=3.8
```

2021-11-04 12:44 UTC, TonioF requested changes
See my comments. Also, 'test_custom_region' in test_index.py fails on my local machine. I'd like to wait to see whether it works on Appveyor.

2021-11-04 12:52 UTC, AliceBalfanz commented on .github/workflows/cate-workflow.yml
> +        name: build-push-docker-image
Not sure, what the consequences of this would be, I took Helges changes... so the docker stuff is mostly his stuff :)

2021-11-05 08:44 UTC, TonioF commented on .github/workflows/cate-workflow.yml
> +        name: build-push-docker-image
I compared this to the workflow in xcube. There, a differentiation was made between latest and release, which I found more telling.

2021-11-05 09:48 UTC, merged