Fixed problem with unsupported time format for permafrost datasets #944
CCI-Tools/cate pull request #945
Opened 2020-09-09 12:52 UTC by AliceBalfanz

Fixed problem with unsupported time format for permafrost datasets #944

2020-09-09 15:17 UTC, TonioF requested changes
There is no need to put get_timestamp_from_string in a try/except-clause. The method takes care of exception handling.

2020-09-11 07:13 UTC, forman requested changes

2020-09-11 07:13 UTC, forman commented on CHANGES.md
> +* Fixed problem with unsupported time format for permafrost datasets #944
Afaik, there is no CCI ECV "permafrost". Please say what datasets are concerned, e.g. provide an ID pattern or so, so people can understand what now work and what was broken..

2020-09-14 12:25 UTC, forman approved these changes

2020-09-14 18:02 UTC, merged