Dzelge 973 hide secrets
CCI-Tools/cate pull request #974
Opened 2021-01-14 14:42 UTC by dzelge

When accepting this PR the cate op `read_zarr` will use the type `Password` for the bucket secret or token

2021-01-14 15:46 UTC, forman requested changes
Please use `password` attribute passed to `@op_input` decorator.

2021-01-14 15:46 UTC, forman commented on cate/ops/io.py
>  @op_input('drop_variables', data_type=VarNamesLike)
That is the intended way

```suggestion
@op_input('drop_variables', data_type=VarNamesLike)
@op_input('secret', data_type=str, password=True)
@op_input('token', data_type=str, password=True)
```

2021-01-14 15:46 UTC, forman commented on cate/core/types.py
> +
Sorry, that is not the intended way.

2021-01-14 15:46 UTC, forman commented on CHANGES.md
> +* read_zarr is now using type `Password` for the bucket secret or token
```suggestion
* Operation `read_zarr()` now uses the new `password` attribute its `secret`and `token` parameters.
```

2021-01-15 09:46 UTC, TonioF requested changes
The entry in changes.md is not understandable. It seems like one word is missing.
Otherwise okay.

2021-02-11 08:45 UTC, forman approved these changes

2021-02-24 07:55 UTC, forman approved these changes

2021-02-24 07:55 UTC, merged